import { AgentMailClient } from 'agentmail';
const inbox = 'steward-agent@agentmail.to';
const safe = (s) =>
  String(s).replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
  );
let client;
function getClient() {
  return (client ??= new AgentMailClient({
    apiKey: process.env.AGENTMAIL_API_KEY,
    maxRetries: 0,
    timeoutInSeconds: 8,
  }));
}
export function mailConfigured() {
  return !!(
    process.env.AGENTMAIL_API_KEY &&
    process.env.APPROVAL_EMAIL &&
    process.env.PUBLIC_BASE_URL
  );
}
export async function sendApproval(run, url) {
  if (!mailConfigured())
    return {
      channel: 'local',
      delivery: 'local-link',
      reason: 'Configure AgentMail and a public URL for phone email.',
    };
  if (!/^https:\/\//.test(process.env.PUBLIC_BASE_URL))
    throw new Error('Phone email requires a public HTTPS approval URL');
  const subject = 'STEWARD · One decision: get home tonight (+$92 net)';
  const text = `Vincent, your SFO → JFK flight was cancelled.\n\nSteward recommends an alternative flight tonight at 9:40 PM.\n$504 new fare − $412 original fare refund = $92 net incremental cost.\n\nYour 9 AM meeting with Sarah is preserved.\nYour 31,000 miles stay available for December.\nYour $412 cash refund is protected.\n\nApprove Steward’s plan: ${url}\n\nThis link expires in 30 minutes. One approval authorizes a simulated booking and refund request. No real purchases or payments.\n\nWhen plans break, Steward fixes them.`;
  const html = `<div style="background:#111914;color:#f0f0df;padding:40px;font-family:Arial,sans-serif;max-width:520px"><div style="letter-spacing:3px;font-weight:bold">STEWARD</div><p style="color:#c1dba2;font-size:11px;margin-top:35px">ONE DECISION NEEDS YOU</p><h1 style="font-size:38px;font-weight:normal">Get home tonight.</h1><p>Alternative flight · Tonight, 9:40 PM</p><h2>+$92 NET</h2><p style="color:#a4ae9b">$504 new fare − $412 original fare refund</p><p>✓ 9 AM meeting with Sarah preserved<br><br>✓ 31,000 miles preserved for December<br><br>✓ $412 cash refund protected</p><a href="${safe(url)}" style="display:block;background:#c1dba2;color:#111914;text-decoration:none;padding:20px;margin:30px 0;text-align:center;font-weight:bold">APPROVE STEWARD’S PLAN ↗</a><p style="font-size:11px;color:#a4ae9b">Expires in 30 minutes. One approval authorizes a simulated booking and refund request. No real purchases or payments.</p><p style="font-size:11px">When plans break, Steward fixes them.</p></div>`;
  const result = await getClient().inboxes.messages.send(
    inbox,
    { to: [process.env.APPROVAL_EMAIL], subject, text, html, labels: ['steward-approval'] },
    { idempotencyKey: `steward-approval-${run.id}` },
  );
  run.messages.push({
    kind: 'decision.sent',
    channel: 'email',
    at: new Date().toISOString(),
    messageId: result.messageId,
    threadId: result.threadId,
  });
  return {
    channel: 'email',
    delivery: 'sent',
    messageId: result.messageId,
    threadId: result.threadId,
  };
}
export async function sendWorkflowMessage(run, kind) {
  return { channel: 'sandbox', delivery: 'received', kind };
}
// The deterministic sandbox airline uses the existing inbox as its real event transport.
// Subject and body are generated by us; unrelated inbox mail is never interpreted as commands.
export async function sendCancellation(run) {
  const subject = `[STEWARD SANDBOX] Flight cancelled ${run.id}`;
  const result = await getClient().inboxes.messages.send(
    inbox,
    {
      to: [inbox],
      subject,
      text: JSON.stringify({
        type: 'flight.cancelled',
        runId: run.id,
        flight: 'SFO-JFK',
        sandbox: true,
      }),
      labels: ['steward-cancellation'],
    },
    { idempotencyKey: `steward-cancel-${run.id}` },
  );
  let received;
  const deadline = Date.now() + 12000;
  while (Date.now() < deadline) {
    const page = await getClient().inboxes.messages.list(inbox, {
      limit: 20,
      subject: [subject],
      from: [inbox],
    });
    received = page.messages.find((m) => m.subject === subject && m.labels.includes('received'));
    if (received) break;
    await new Promise((resolve) => setTimeout(resolve, 800));
  }
  if (!received) throw Error('AgentMail cancellation delivery not confirmed');
  const message = await getClient().inboxes.messages.get(inbox, received.messageId);
  const content = message.extractedText ?? message.text;
  let payload;
  try {
    payload = JSON.parse(content);
  } catch {
    throw Error('Cancellation event payload unavailable');
  }
  if (payload.type !== 'flight.cancelled' || payload.runId !== run.id || payload.sandbox !== true)
    throw Error('Cancellation event mismatch');
  return {
    channel: 'agentmail',
    messageId: message.messageId,
    threadId: message.threadId,
    source: 'Sandbox airline · AgentMail event',
  };
}
