import { AgentMailClient } from 'agentmail';
const inbox = 'steward-agent@agentmail.to';
const safe = (s) =>
  String(s).replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
  );
let client;
function getClient() {
  return (client ??= new AgentMailClient({
    apiKey: process.env.AGENTMAIL_API_KEY,
    maxRetries: 0,
    timeoutInSeconds: 8,
  }));
}
export function mailConfigured() {
  return !!(
    process.env.AGENTMAIL_API_KEY &&
    process.env.APPROVAL_EMAIL &&
    process.env.PUBLIC_BASE_URL
  );
}
export async function sendApproval(run, url) {
  if (!mailConfigured())
    return {
      channel: 'local',
      delivery: 'local-link',
      reason: 'Configure AgentMail and a public URL for phone email.',
    };
  if (!/^https:\/\//.test(process.env.PUBLIC_BASE_URL))
    throw new Error('Phone email requires a public HTTPS approval URL');
  const subject = 'Steward needs one decision';
  const text = `STEWARD\n\nOne decision needs you.\n\nFlight disruption detected\nSFO → JFK\n\nSTEWARD RECOMMENDS\nGET HOME TONIGHT\n\nAlternative flight · 9:40 PM\nNet additional cost: $92\n\n✓ 9 AM commitment preserved\n✓ 31,000 miles preserved\n✓ refund protected\n\nAPPROVE PLAN: ${url}\n\nSteward will handle the rest.\n\nSigned link expires in 30 minutes. Sandbox booking and refund only; no real purchases or payments.`;
  const html = `<div style="background:#f6f7fb;color:#171d2b;padding:32px;font-family:Arial,sans-serif;max-width:520px;margin:auto"><div style="letter-spacing:4px;font-size:20px">STEWARD</div><p style="margin-top:28px">One decision needs you.</p><p style="color:#657183">Flight disruption detected<br>SFO → JFK</p><p style="font-size:11px;letter-spacing:2px;color:#3450df;margin-top:28px">STEWARD RECOMMENDS</p><h1 style="font-size:32px;font-weight:normal">Get home tonight.</h1><p>Alternative flight · 9:40 PM<br>Net additional cost: <strong>$92</strong></p><p style="line-height:2">✓ 9 AM commitment preserved<br>✓ 31,000 miles preserved<br>✓ refund protected</p><a href="${safe(url)}" style="display:block;background:#3450df;color:#fff;text-decoration:none;padding:18px;margin:24px 0;text-align:center;border-radius:8px;font-weight:bold">APPROVE PLAN</a><p>Steward will handle the rest.</p><p style="font-size:11px;color:#657183;line-height:1.5">Signed link expires in 30 minutes. Sandbox booking and refund only. No real purchases or payments.</p></div>`;
  const result = await getClient().inboxes.messages.send(
    inbox,
    { to: [process.env.APPROVAL_EMAIL], subject, text, html, labels: ['steward-approval'] },
    { idempotencyKey: `steward-approval-${run.id}` },
  );
  run.messages.push({
    kind: 'decision.sent',
    channel: 'email',
    at: new Date().toISOString(),
    messageId: result.messageId,
    threadId: result.threadId,
  });
  return {
    channel: 'email',
    delivery: 'sent',
    messageId: result.messageId,
    threadId: result.threadId,
  };
}
export async function sendWorkflowMessage(run, kind) {
  return { channel: 'sandbox', delivery: 'received', kind };
}
// The deterministic sandbox airline uses the existing inbox as its real event transport.
// Subject and body are generated by us; unrelated inbox mail is never interpreted as commands.
export async function sendCancellation(run) {
  const subject = `[STEWARD SANDBOX] Flight cancelled ${run.id}`;
  const result = await getClient().inboxes.messages.send(
    inbox,
    {
      to: [inbox],
      subject,
      text: JSON.stringify({
        type: 'flight.cancelled',
        runId: run.id,
        flight: 'SFO-JFK',
        sandbox: true,
      }),
      labels: ['steward-cancellation'],
    },
    { idempotencyKey: `steward-cancel-${run.id}` },
  );
  // Self-addressed mail is stored as sent by AgentMail, rather than delivered
  // as a second received message. Read the exact server-issued message ID;
  // that generated mailbox message is the sandbox airline's event transport.
  const message = await getClient().inboxes.messages.get(inbox, result.messageId);
  const content = message.extractedText ?? message.text;
  const protocol = String(content ?? '')
    .split(/\r?\n/)[0]
    .trim();
  let payload;
  try {
    payload = JSON.parse(protocol);
  } catch {
    throw Error('Cancellation event payload unavailable');
  }
  if (payload.type !== 'flight.cancelled' || payload.runId !== run.id || payload.sandbox !== true)
    throw Error('Cancellation event mismatch');
  return {
    channel: 'agentmail',
    messageId: message.messageId,
    threadId: message.threadId,
    source: 'Sandbox airline · AgentMail event',
    evidence: 'Generated cancellation message verified through AgentMail API',
    mailboxDirection: message.labels?.includes('received') ? 'received' : 'sent',
  };
}
